version: '3'
services:
  app:
    image: app:latest
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Dego
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Dego
    ports:
      - "3306:3306"
